client/src/components/Pages/FusionType/FusionType.tsx
client/src/components/Pages/Structure/Builder/Builder.scss
client/src/components/Utilities/UtilitiesNavTabs/UtilitiesNavTabs.scss
client/src/components/main/App/App.scss
client/src/components/main/App/App.tsx
client/src/components/main/Nav/NavTabs.scss
client/src/components/main/Nav/NavTabs.tsx

Layout fixes and cleanup

---

server/setup.cfg
server/tests/integration/test_nomenclature.py

Fixing up a couple small versioning/test case issues to make all tests pass again

test: resolve server-side regressions

---

client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx

fix: handle tx seg input edge cases

---

client/src/components/Utilities/GetSequenceIds/GetSequenceIds.tsx
server/curfu/routers/utilities.py

close #122 
* Also does a little error handling on the sequence fetching end. SeqRepo is stricter about valid input for sequence retrieval than it is for alias retrieval, so we retry with a recognized ID from the latter if the former doesn't work the first time.

feat: add sequence ID demo buttons

---

client/src/components/Pages/Summary/Main/Summary.tsx

close #132 
Can't tell if this actually fixed it, eyes are too old 👎

fix: don't load summary error before checking validity

---

README.md
requirements.txt

Changes can be seen here: http://fusion-curation-dev-eb.us-east-2.elasticbeanstalk.com/

fix: requirements.txt for elastic beanstalk 

---

client/src/components/main/shared/GeneAutocomplete/GeneAutocomplete.tsx

fix: label concept ID matches in gene autocomplete

---

client/src/components/Pages/Summary/Invalid/Invalid.scss
client/src/components/Pages/Summary/Invalid/Invalid.tsx
client/src/components/Pages/Summary/Main/Summary.tsx
client/src/components/main/Nav/NavTabs.tsx

feat: better validation error messages

---

server/curfu/routers/__init__.py
server/curfu/routers/constructors.py
server/tests/integration/test_constructors.py

feat: more forgiving ID parsing

---

client/.env.production

not entirely sure that this will work

fix: correct request path in prod 

---

.ebextensions/02_data_downloads.config

Reverts cancervariants/fusion-curation#208

Revert "fix: update build commands for python 3.11"

---

client/src/components/Pages/Structure/Input/StructuralElementInputAccordion.tsx
client/src/components/main/Nav/NavTabs.tsx
client/src/components/main/shared/ChromosomeField/ChromosomeField.tsx
client/src/components/main/shared/GeneAutocomplete/GeneAutocomplete.tsx
client/src/components/main/shared/StrandSwitch/StrandSwitch.tsx
client/src/components/main/shared/TranscriptField/TranscriptField.tsx

* fix: fixing issue where continue button was on summary tab, fixing issue where clear button for autocomplete would appear when nothing was entered
* fix: fixing ui issue where components would overlay with helper text and be illegible
* fix: fixing ui issue where components would overlay with helper text and be illegible
* fix: styling fixes and tooltip data fix
* styling: removing console log
* refactor: making props optional
* reverting unneeded change
* fix: making gene autocomplete wider for better readability and to fix wrapping issue
* feat: adjusting icons on components to make more sense
* feat: adjusting strand switch color to be more readable
* fix: editing padding on card components

fix: fixing ui issues such as incorrect displays and readability issues

---

client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx

fix: display error for out-of-range exons

---

client/src/components/Pages/CausativeEvent/CausativeEvent.tsx
client/src/components/Pages/Structure/Input/StructuralElementInputAccordion.tsx
client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx
client/src/components/main/App/App.scss
client/src/components/main/App/App.tsx
client/src/components/main/App/AppMenu.tsx
client/src/components/main/shared/GeneAutocomplete/GeneAutocomplete.tsx
client/src/components/main/shared/HelpTooltip/HelpTooltip.tsx
client/src/global/contexts/SettingsContext.tsx
client/src/global/styles/theme.ts

* should they be enabled by default?
* menu bar formatting?

feat: optionally enable tooltips

---

client/src/components/Pages/Summary/Invalid/Invalid.tsx

fix: adding validation to disallow same-gene fusions

---

client/src/components/Pages/Summary/Invalid/Invalid.tsx

* fix: adding validation to disallow same-gene fusions
* remove console log
* fix: adding validation to disallow same-gene fusions
* fix: fixing console error for unique keys

fix: adding validation to disallow same-gene fusions (#251)

---

server/curfu/main.py
server/curfu/routers/complete.py
server/curfu/routers/constructors.py
server/curfu/routers/demo.py
server/curfu/routers/lookup.py
server/curfu/routers/meta.py
server/curfu/routers/nomenclature.py
server/curfu/routers/utilities.py
server/curfu/routers/validate.py
server/curfu/schemas.py

Minor aesthetic fix: makes the API page a bit more readable (see http://127.0.0.1:5000/docs)

docs: update API doc organization

---

server/pyproject.toml

In hindsight, this wasn't too surprising

build: fix setuptools-scm build

---

client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx

while looking into #323 I noticed a bug in the get coordinates utility.

fix: get coordinates not working for transcript

---

client/src/components/Pages/Structure/Input/TemplatedSequenceElementInput/TemplatedSequenceElementInput.tsx
client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx
server/src/curfu/routers/utilities.py

All commits have been approved already.

Migrate staging changes to main
